default: &default
  adapter: mysql2
  encoding: utf8mb4
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sake_user
  password: password
  timeout: 5000

development:
  <<: *default
  database: sake_development
  database: sake_development

test:
  <<: *default
  database: sake_test
  database: sake_test

production:
  <<: *default
  database: sake_production
  username: <%= ENV['SAKE_DATABASE_USER'] %>
  password: <%= ENV['SAKE_DATABASE_PASSWORD'] %>
